# -*- coding: utf-8 -*-
"""Copy of nn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-A7E_u2UbdGQktOo9csSesA1OM_ZXEf0
"""

pip install complexPyTorch

from google.colab import drive
drive.mount("/content/gdrive")

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms

from torch.nn import BatchNorm2d, Conv2d, Linear
from torch.nn.functional import relu, max_pool2d
from torch.utils.data import DataLoader, TensorDataset, Subset

from complexPyTorch.complexLayers import ComplexBatchNorm2d, ComplexConv2d, ComplexLinear
from complexPyTorch.complexFunctions import complex_relu, complex_max_pool2d, complex_avg_pool2d


#import pyMMF
import numpy as np
import matplotlib.pyplot as plt
import time
import sys
import math
import cmath

OUTPUT_MODES = 5

BATCH_SIZE = 32
EPOCHS = 200

x = torch.tensor(np.load('/content/gdrive/My Drive/x.npy'),dtype=torch.complex64)
y = torch.tensor(np.load('/content/gdrive/My Drive/y.npy'),dtype=torch.complex64)
#real_part = np.real(y)
#imaginary_part = np.imag(y)

# Stack them horizontally to get real and imaginary parts as separate values
#y = torch.tensor(np.hstack((real_part, imaginary_part)),dtype=torch.float32)

print(x.shape, y.shape)
print(x.dtype, y.dtype)
#print(x)
print(y)


dataset = TensorDataset(x, y)
#train_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

train_data, test_data, val_data = torch.utils.data.random_split(dataset,[0.72, 0.2, 0.08])

train_loader = DataLoader(train_data, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_data, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_data, batch_size=BATCH_SIZE, shuffle=True)

class ComplexNet(nn.Module):

    def __init__(self, output_modes, kernel_size):
        super(ComplexNet, self).__init__()
        '''
        self.conv1 = ComplexConv2d(1, 8,kernel_size)
        self.bn1  = ComplexBatchNorm2d(8)
        self.size_1 = int(np.floor((128 - kernel_size + 1 - 2)/2) + 1)

        self.conv2 = ComplexConv2d(8, 16,kernel_size)
        self.bn2  = ComplexBatchNorm2d(16)
        self.size_2 = int(np.floor((self.size_1 - kernel_size + 1 - 2)/2) + 1)

        self.conv3 = ComplexConv2d(16, 32,kernel_size)
        self.bn3  = ComplexBatchNorm2d(32)
        self.size_3 = int(np.floor((self.size_2 - kernel_size + 1 - 2)/2) + 1)

        self.fc1 = ComplexLinear(self.size_3*self.size_3*32, output_modes)
        '''
        self.fc_single = ComplexLinear(128*128, output_modes)

    def forward(self,x):
        '''x = x.view(x.size(0), 1,x.size(1),x.size(2))
        print(x.shape)

        x = self.conv1(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn1(x)

        x = self.conv2(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn2(x)

        x = self.conv3(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn3(x)
        '''
        x = x.view(-1,128*128)
        x = self.fc_single(x)
        '''print(x.shape)
        x = x.view(self.size_3*self.size_3*32)
        x = self.fc1(x)'''
        #x = x.abs()
        #x =  F.log_softmax(x, dim=1)
        return x

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = ComplexNet(kernel_size = 3, output_modes = OUTPUT_MODES).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)#, momentum=0.9)

train_losses = []
val_losses = []
def criterion(x, y):
    """
    Calculate the mean square error between two complex numbers of type torch.complex64.

    Args:
    x (torch.complex64): The first complex number.
    y (torch.complex64): The second complex number.

    Returns:
    mse (torch.float32): The mean square error between x and y.
    """
    # Calculate the squared difference between real and imaginary parts
    real_diff = torch.square(torch.real(x) - torch.real(y))
    imag_diff = torch.square(torch.imag(x) - torch.imag(y))

    # Calculate the mean square error
    mse = torch.mean(real_diff + imag_diff)
    #return (0.5*(x - y)**2).mean(dtype=torch.complex64)
    return mse

def eval(model, device, data_loader):
    model.eval()
    loss = 0
    for batch_idx, (data, target) in enumerate(data_loader):
        with torch.no_grad():
            data, target = data.to(device), target.to(device)
            output = model(data)

            loss += criterion(output, target)

    model.train()
    return loss/len(data_loader)


def train(model, device, train_loader, optimizer, epoch):
    model.train()
    epoch_loss = 0
    epoch_val_loss = 0
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)

        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        val_loss = eval(model, device, val_loader)
        print('\rTrain Epoch: {:3} [({:3.0f}%)]\tLoss: {:.6f}\tValidation Loss: {:.6f}'.format(
                epoch,
                100. * batch_idx / len(train_loader),
                loss.item(),
                val_loss),
              end = ' '
        )
        epoch_loss = loss.item()
        epoch_val_loss = eval(model, device, val_loader).cpu().numpy()
    train_losses.append(loss.item())
    val_losses.append(eval(model, device, val_loader).cpu().numpy())
    print('')

# Run training on 50 epochs
for epoch in range(EPOCHS):
    train(model, device, train_loader, optimizer, epoch)

plt.plot(range(len(train_losses)-2), train_losses[2:], label='Train Losses')
#val_losses = [tensor_item.cpu().numpy().item() for tensor_item in val_losses]
plt.plot(range(len(train_losses)-2), val_losses[2:], label='Validation Losses')

plt.xlabel('Batches')
plt.ylabel('Loss')

plt.title('Train and Validation Losses')

plt.legend()
plt.show()

def correlation_fn(out,gt):

    corrs = []

    # Apply fn1 to corresponding complex number pairs element-wise
    for y, y0 in zip(out, gt):
        '''print(out)
        print(gt)
        print(y)
        print(y0)
        '''
        corr = complex_correlation(y.cpu().numpy(), y0.cpu().numpy())
        corrs.append(corr)

    return corrs

def complex_correlation(y,y0):

    a = abs(y)
    theta = cmath.phase(y)

    b = abs(y0)
    phi = cmath.phase(y0)
    # Construct complex numbers x and y
    x = a * cmath.exp(1j * theta)  # x = a * e^(j * theta)
    y = b * cmath.exp(1j * phi)    # y = b * e^(j * phi)

    # Calculate x.conjugate() * y
    correlation = x.conjugate() * y

    # Extract amplitude and phase difference
    amplitude = abs(correlation)
    phase_diff = cmath.phase(correlation)

    # Calculate the real part of the correlation
    real_part = amplitude * math.cos(phase_diff)

    return real_part

import locale
locale.getpreferredencoding = lambda: "UTF-8"
!pip install pyMMF

import pyMMF
import numpy as np
import matplotlib.pyplot as plt
import time

# Find modes of an MMF
NA = 0.1
radius = 4 # in microns
areaSize = 2.5*radius # calculate the field on an area larger than the diameter of the fiber
npoints = 2**7 # resolution of the window
n1 = 1.45
wl = 0.589 # wavelength in microns
curvature = None
profile = pyMMF.IndexProfile(npoints = npoints, areaSize = areaSize)
profile.initStepIndex(n1=n1, a=radius, NA=NA)

solver = pyMMF.propagationModeSolver()
solver.setIndexProfile(profile)
solver.setWL(wl)
NmodesMax = pyMMF.estimateNumModesSI(wl,radius,NA,pola = 1)
print(NmodesMax)
modes = solver.solve (mode = 'SI', curvature = None)
modes.sort() # sort modes by descending beta constants

m = 2
plt.figure()
plt.subplot(121)
plt.imshow(np.abs(modes.profiles[m]).reshape([npoints]*2))
plt.title('Amplitude')
plt.subplot(122)
plt.imshow(np.angle(modes.profiles[m]).reshape([npoints]*2))
plt.title('Phase')


# show first n modes to check order of sort
plt.figure()
for i in range(NmodesMax):
    plt.subplot(7,7,i+1)
    plt.imshow(np.abs(modes.profiles[i].reshape([npoints]*2)))

def plot_fn(out_from_test):#output of nn for single image: 5 modes
# generate variable 'modes' using pymmf solver for 5 modes

  a = []
  phi = []
  for y in out_from_test:
      a.append(abs(y.cpu().numpy()))
      phi.append(cmath.phase(y))
  #print(a)
  #print(phi)
  weights = out_from_test.cpu().numpy()#a * np.exp(1j * phi)

  #print('Vector of mode weights:')
  #print(weights)

  #Create Superposition
  superpos = sum(weights[i] * modes.profiles[i] for i in range(NmodesMax))


  # Calculate intensity in MMF
  intensity = superpos * np.conj(superpos)
  intensity = np.real(intensity) # only to change data type from complex to float

  # Visualize the superposition
  plt.figure()
  plt.subplot(131)
  plt.imshow(np.abs(superpos).reshape([npoints] * 2))
  plt.title('Amplitude')
  plt.axis('off')

  plt.subplot(132)
  plt.imshow(np.angle(superpos).reshape([npoints] * 2))
  plt.title('Phase')
  plt.axis('off')

  plt.subplot(133)
  plt.imshow(intensity.reshape([npoints] * 2))
  plt.title('Intensity')
  plt.axis('off')

  plt.show()
  return intensity

model.eval()
test_losses = 0
correlation_values = []
fidelity_values = []
with torch.no_grad():
    correct = 0;
    total = 0;
    i = 0
    for X, y in test_loader:

        X, y = X.to(device), y.to(device);
        out = model(X);
        test_losses += criterion(out, y)
        for out_single, y_single in zip(out,y):
            i = i+1
            print('Test image {:3}:'.format(i), end = ' ')
            pred_int = plot_fn(out_single)
            print('Ground Truth image {:3}:'.format(i), end = ' ')
            gt_int = plot_fn(y_single)

            r=np.corrcoef(pred_int,gt_int)

            correlation_values.append(r[1,0])
            print(correlation_values[i-1])

import torch

# Function to calculate fidelity
def calculate_fidelity(outputs, ground_truths):
    fidelities = []

    # Iterate through each output and ground truth pair
    for output, ground_truth in zip(outputs, ground_truths):
        # Normalize output and ground truth samples
        output_norm = output / torch.norm(output)
        ground_truth_norm = ground_truth / torch.norm(ground_truth)

        # Calculate inner product
        inner_product = torch.dot(output_norm, ground_truth_norm)

        # Calculate fidelity (square of absolute value of inner product)
        fidelity = torch.abs(inner_product) ** 2

        # Append fidelity to list
        fidelities.append(fidelity.item())  # Convert to scalar value

    return fidelities

model.eval()
test_losses = 0
correlation_values = []
fidelity_values = []  # Store fidelity values
with torch.no_grad():
    correct = 0
    total = 0
    i = 0
    for X, y in test_loader:

        X, y = X.to(device), y.to(device)
        out = model(X)
        test_losses += criterion(out, y)
        for out_single, y_single in zip(out, y):
            i = i + 1
            print('Test image {:3}:'.format(i), end=' ')
            pred_int = plot_fn(out_single)
            print('Ground Truth image {:3}:'.format(i), end=' ')
            gt_int = plot_fn(y_single)

            # Calculate correlation coefficient
            r = np.corrcoef(pred_int, gt_int)
            correlation_values.append(r[1, 0])
            print('Correlation:', correlation_values[i - 1])

            # Calculate fidelity
            fidelity = np.abs(np.sum(np.conj(pred_int) * gt_int)) / (
                        np.sqrt(np.sum(np.abs(pred_int) ** 2)) * np.sqrt(np.sum(np.abs(gt_int) ** 2)))
            fidelity_values.append(fidelity)
            print('Fidelity:', fidelity)

    print('Testing Loss = ', end=' ')
    print((test_losses / len(test_loader)).cpu().numpy())

# Calculate average fidelity
avg_fidelity = np.mean(fidelity_values)
print('Average Fidelity:', avg_fidelity)

# Generate graphs
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.plot(correlation_values, label='Correlation')
plt.xlabel('Image Index')
plt.ylabel('Correlation')
plt.title('Correlation Values')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(fidelity_values, label='Fidelity')
plt.xlabel('Image Index')
plt.ylabel('Fidelity')
plt.title('Fidelity Values')
plt.legend()

plt.tight_layout()
plt.show()

pip install seaborn

import matplotlib.pyplot as plt
import seaborn as sns
# Distribution plot for Correlation
plt.subplot(2, 2, 3)
sns.histplot(correlation_values, kde=True, bins=10)
plt.xlabel('Correlation')
plt.ylabel('Frequency')
plt.title('Distribution of Correlation Values')

# Distribution plot for Fidelity
plt.subplot(2, 2, 4)
sns.histplot(fidelity_values, kde=True, bins=10)
plt.xlabel('Fidelity')
plt.ylabel('Frequency')
plt.title('Distribution of Fidelity Values')

plt.tight_layout()
plt.show()

# Distribution plot for Correlation
plt.subplot(2, 3, 3)
sns.histplot(correlation_values, kde=True, bins=10)
plt.xlabel('Correlation')
plt.ylabel('Frequency')
plt.title('Distribution of Correlation Values')

# Distribution plot for Fidelity
plt.subplot(2, 3, 4)
sns.histplot(fidelity_values, kde=True, bins=10)
plt.xlabel('Fidelity')
plt.ylabel('Frequency')
plt.title('Distribution of Fidelity Values')

# Image Index vs Correlation
plt.subplot(2, 3, 5)
sns.scatterplot(x=range(len(correlation_values)), y=correlation_values)
plt.xlabel('Image Index')
plt.ylabel('Correlation')
plt.title('Image Index vs Correlation')

# Image Index vs Fidelity
plt.subplot(2, 3, 6)
sns.scatterplot(x=range(len(fidelity_values)), y=fidelity_values)
plt.xlabel('Image Index')
plt.ylabel('Fidelity')
plt.title('Image Index vs Fidelity')

plt.tight_layout()
plt.show()

"""@@@@@@@@@@@@@@@@script ends here

"""

print(y)

pip install complexPyTorch

# Necessary imports
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, TensorDataset, random_split
import numpy as np
import matplotlib.pyplot as plt

from complexPyTorch.complexLayers import ComplexBatchNorm2d, ComplexConv2d, ComplexLinear
from complexPyTorch.complexFunctions import complex_relu, complex_max_pool2d, complex_avg_pool2d

# Define constants
OUTPUT_MODES = 5
BATCH_SIZE = 32
EPOCHS = 200

# Mount Google Drive
from google.colab import drive
drive.mount("/content/gdrive")

# Load data
x = torch.tensor(np.load('/content/gdrive/My Drive/x.npy'), dtype=torch.complex64)
y = torch.tensor(np.load('/content/gdrive/My Drive/y.npy'), dtype=torch.complex64)

print(x.shape, y.shape)
print(x.dtype, y.dtype)
print(y)

# Create dataset and data loaders
dataset = TensorDataset(x, y)
train_size = int(0.72 * len(dataset))
test_size = int(0.2 * len(dataset))
val_size = len(dataset) - train_size - test_size

train_data, test_data, val_data = random_split(dataset, [train_size, test_size, val_size])

train_loader = DataLoader(train_data, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_data, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_data, batch_size=BATCH_SIZE, shuffle=True)

# Define the ComplexNet model
class ComplexNet(nn.Module):
    def __init__(self, output_modes):
        super(ComplexNet, self).__init__()
        self.fc_single = ComplexLinear(128 * 128, output_modes)

    def forward(self, x):
        x = x.view(-1, 128 * 128)
        x = self.fc_single(x)
        return x

# Define loss function and evaluation function
def criterion(x, y):
    real_diff = torch.square(torch.real(x) - torch.real(y))
    imag_diff = torch.square(torch.imag(x) - torch.imag(y))
    mse = torch.mean(real_diff + imag_diff)
    return mse

def eval(model, device, data_loader):
    model.eval()
    loss = 0
    with torch.no_grad():
        for data, target in data_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            loss += criterion(output, target).item()
    return loss / len(data_loader)

# Define training function
def train(model, device, train_loader, optimizer, epoch):
    model.train()
    epoch_loss = 0
    for data, target in train_loader:
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    val_loss = eval(model, device, val_loader)
    print(f'Train Epoch: {epoch} \tLoss: {epoch_loss / len(train_loader):.6f}\tValidation Loss: {val_loss:.6f}')

    train_losses.append(epoch_loss / len(train_loader))
    val_losses.append(val_loss)

# Setup device, model, optimizer, and training loop
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = ComplexNet(output_modes=OUTPUT_MODES).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

train_losses = []
val_losses = []

# Run training for defined epochs
for epoch in range(EPOCHS):
    train(model, device, train_loader, optimizer, epoch)

# Plot training and validation losses
plt.plot(range(len(train_losses)), train_losses, label='Train Losses')
plt.plot(range(len(val_losses)), val_losses, label='Validation Losses')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Train and Validation Losses')
plt.legend()
plt.show()

