# -*- coding: utf-8 -*-
"""Normal Distribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SeEptCv4WHInInTnT4dlAjggxo-MQjHW
"""

pip install pyMMF

import pyMMF
import numpy as np
import matplotlib.pyplot as plt
import time

# Find modes of an MMF
NA = 0.1
radius = 12.5 # in microns
areaSize = 2.5*radius # calculate the field on an area larger than the diameter of the fiber
npoints = 2**7 # resolution of the window
n1 = 1.45
wl = 0.532 # wavelength in microns
curvature = None

profile = pyMMF.IndexProfile(npoints = npoints, areaSize = areaSize)
profile.initStepIndex(n1=n1, a=radius, NA=NA)

solver = pyMMF.propagationModeSolver()
solver.setIndexProfile(profile)
solver.setWL(wl)

NmodesMax = pyMMF.estimateNumModesSI(wl,radius,NA,pola = 1)

modes = solver.solve (mode = 'SI', curvature = None)
modes.sort() # sort modes by descending beta constants

#Set the number of modes and generate a random complex matrix
random_matrix = np.random.rand(NmodesMax, NmodesMax) + 1j * np.random.rand(NmodesMax, NmodesMax)

 #Perform Singular Value Decomposition (SVD)
U, S, V = np.linalg.svd(random_matrix)
TM = U
print("Random complex matrix U from SVD:")
print(U)

# Number of modes in the few-mode fiber
total_modes = 5

# Initialize the matrix to store the few-mode vectors
fiber_modes_matrix = []
GROUND_TRUTH = []

# Create random amplitude and phase for few-mode-number of modes
for _ in range(1000):
    a = np.random.normal(0, 1, size=total_modes)
    phi = np.random.uniform(0, 2 * np.pi, size=total_modes)
    phi[0] = 0

    # complex vector
    fiber_modes_nn = a * np.exp(1j * phi)
    fiber_modes_nn = fiber_modes_nn / np.linalg.norm(fiber_modes_nn)
    GROUND_TRUTH.append(fiber_modes_nn)

    # pad few-mode vector to multimode vector
    fiber_modes = np.pad(fiber_modes_nn, (0, NmodesMax - len(fiber_modes_nn)), 'constant')

    # Append the vector to the matrix
    fiber_modes_matrix.append(fiber_modes)

GROUND_TRUTH = np.array(GROUND_TRUTH)

# Convert the matrix to a numpy array
fiber_modes_matrix = np.array(fiber_modes_matrix)

# Display the generated few-mode vectors
print("Few-Mode Vectors Matrix:")
print(fiber_modes_matrix.shape)

INPUTS = []
# Loop over each vector and calculate the superposition and intensity
for i in range(1000):
    fiber_modes = fiber_modes_matrix[i]

    # Calculate the MMF output vector y as y = TM * x
    y = np.dot(fiber_modes, TM)

    # Superposition of modes
    superpos = sum(y[j] * modes.profiles[j] for j in range(NmodesMax))

    # Check the shape of superpos
    print(f"Superposition shape (iteration {i}):", superpos.shape)

    # Calculate the intensity
    intensity = np.abs(superpos) ** 2

    # Check the shape of intensity
    print(f"Intensity shape (iteration {i}):", intensity.shape)

    INPUTS.append(intensity.reshape([npoints] * 2))

# Convert INPUTS to a tensor
INPUTS = np.array(INPUTS)
print("INPUTS shape:", INPUTS.shape)

pip install complexPyTorch

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms

from torch.nn import BatchNorm2d, Conv2d, Linear
from torch.nn.functional import relu, max_pool2d
from torch.utils.data import DataLoader, TensorDataset, Subset

from complexPyTorch.complexLayers import ComplexBatchNorm2d, ComplexConv2d, ComplexLinear
from complexPyTorch.complexFunctions import complex_relu, complex_max_pool2d, complex_avg_pool2d


#import pyMMF
import numpy as np
import matplotlib.pyplot as plt
import time
import sys
import math
import cmath

# Prepare the dataset for training
INPUTS = torch.tensor(INPUTS, dtype=torch.complex64)
GROUND_TRUTH = torch.tensor(GROUND_TRUTH, dtype=torch.complex64)

# Check tensor sizes to ensure they match
print(INPUTS.shape, GROUND_TRUTH.shape)

# Ensure both tensors have the same number of samples
assert INPUTS.size(0) == GROUND_TRUTH.size(0), f"Size mismatch: {INPUTS.size(0)} != {GROUND_TRUTH.size(0)}"

dataset = TensorDataset(INPUTS, GROUND_TRUTH)
train_data, test_data, val_data = torch.utils.data.random_split(dataset,[0.72, 0.2, 0.08])

train_loader = DataLoader(train_data, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_data, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_data, batch_size=BATCH_SIZE, shuffle=True)

class ComplexNet(nn.Module):

    def __init__(self, output_modes, kernel_size):
        super(ComplexNet, self).__init__()
        '''
        self.conv1 = ComplexConv2d(1, 8,kernel_size)
        self.bn1  = ComplexBatchNorm2d(8)
        self.size_1 = int(np.floor((128 - kernel_size + 1 - 2)/2) + 1)

        self.conv2 = ComplexConv2d(8, 16,kernel_size)
        self.bn2  = ComplexBatchNorm2d(16)
        self.size_2 = int(np.floor((self.size_1 - kernel_size + 1 - 2)/2) + 1)

        self.conv3 = ComplexConv2d(16, 32,kernel_size)
        self.bn3  = ComplexBatchNorm2d(32)
        self.size_3 = int(np.floor((self.size_2 - kernel_size + 1 - 2)/2) + 1)

        self.fc1 = ComplexLinear(self.size_3*self.size_3*32, output_modes)
        '''
        self.fc_single = ComplexLinear(128*128, output_modes)

    def forward(self,x):
        '''x = x.view(x.size(0), 1,x.size(1),x.size(2))
        print(x.shape)

        x = self.conv1(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn1(x)

        x = self.conv2(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn2(x)

        x = self.conv3(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn3(x)
        '''
        x = x.view(-1,128*128)
        x = self.fc_single(x)
        '''print(x.shape)
        x = x.view(self.size_3*self.size_3*32)
        x = self.fc1(x)'''
        #x = x.abs()
        #x =  F.log_softmax(x, dim=1)
        return x

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = ComplexNet(kernel_size = 3, output_modes = OUTPUT_MODES).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)#, momentum=0.9)

train_losses = []
val_losses = []
def criterion(x, y):
    """
    Calculate the mean square error between two complex numbers of type torch.complex64.

    Args:
    x (torch.complex64): The first complex number.
    y (torch.complex64): The second complex number.

    Returns:
    mse (torch.float32): The mean square error between x and y.
    """
    # Calculate the squared difference between real and imaginary parts
    real_diff = torch.square(torch.real(x) - torch.real(y))
    imag_diff = torch.square(torch.imag(x) - torch.imag(y))

    # Calculate the mean square error
    mse = torch.mean(real_diff + imag_diff)
    #return (0.5*(x - y)**2).mean(dtype=torch.complex64)
    return mse

def eval(model, device, data_loader):
    model.eval()
    loss = 0
    for batch_idx, (data, target) in enumerate(data_loader):
        with torch.no_grad():
            data, target = data.to(device), target.to(device)
            output = model(data)

            loss += criterion(output, target)

    model.train()
    return loss/len(data_loader)


def train(model, device, train_loader, optimizer, epoch):
    model.train()
    epoch_loss = 0
    epoch_val_loss = 0
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)

        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        val_loss = eval(model, device, val_loader)
        print('\rTrain Epoch: {:3} [({:3.0f}%)]\tLoss: {:.6f}\tValidation Loss: {:.6f}'.format(
                epoch,
                100. * batch_idx / len(train_loader),
                loss.item(),
                val_loss),
              end = ' '
        )
        epoch_loss = loss.item()
        epoch_val_loss = eval(model, device, val_loader).cpu().numpy()
    train_losses.append(loss.item())
    val_losses.append(eval(model, device, val_loader).cpu().numpy())
    print('')

# Run training on 50 epochs
for epoch in range(EPOCHS):
    train(model, device, train_loader, optimizer, epoch)

plt.plot(range(len(train_losses)-2), train_losses[2:], label='Train Losses')
#val_losses = [tensor_item.cpu().numpy().item() for tensor_item in val_losses]
plt.plot(range(len(train_losses)-2), val_losses[2:], label='Validation Losses')

plt.xlabel('Batches')
plt.ylabel('Loss')

plt.title('Train and Validation Losses')

plt.legend()
plt.show()

import pyMMF
import numpy as np
import matplotlib.pyplot as plt
import time

# Find modes of an MMF
NA = 0.1
radius = 4 # in microns
areaSize = 2.5*radius # calculate the field on an area larger than the diameter of the fiber
npoints = 2**7 # resolution of the window
n1 = 1.45
wl = 0.589 # wavelength in microns
curvature = None
profile = pyMMF.IndexProfile(npoints = npoints, areaSize = areaSize)
profile.initStepIndex(n1=n1, a=radius, NA=NA)

solver = pyMMF.propagationModeSolver()
solver.setIndexProfile(profile)
solver.setWL(wl)
NmodesMax = pyMMF.estimateNumModesSI(wl,radius,NA,pola = 1)
print(NmodesMax)
modes = solver.solve (mode = 'SI', curvature = None)
modes.sort() # sort modes by descending beta constants

m = 2
plt.figure()
plt.subplot(121)
plt.imshow(np.abs(modes.profiles[m]).reshape([npoints]*2))
plt.title('Amplitude')
plt.subplot(122)
plt.imshow(np.angle(modes.profiles[m]).reshape([npoints]*2))
plt.title('Phase')


# show first n modes to check order of sort
plt.figure()
for i in range(NmodesMax):
    plt.subplot(7,7,i+1)
    plt.imshow(np.abs(modes.profiles[i].reshape([npoints]*2)))

def plot_fn(out_from_test):#output of nn for single image: 5 modes
# generate variable 'modes' using pymmf solver for 5 modes

  a = []
  phi = []
  for y in out_from_test:
      a.append(abs(y.cpu().numpy()))
      phi.append(cmath.phase(y))
  #print(a)
  #print(phi)
  weights = out_from_test.cpu().numpy()#a * np.exp(1j * phi)

  #print('Vector of mode weights:')
  #print(weights)

  #Create Superposition
  superpos = sum(weights[i] * modes.profiles[i] for i in range(NmodesMax))


  # Calculate intensity in MMF
  intensity = superpos * np.conj(superpos)
  intensity = np.real(intensity) # only to change data type from complex to float

  # Visualize the superposition
  plt.figure()
  plt.subplot(131)
  plt.imshow(np.abs(superpos).reshape([npoints] * 2))
  plt.title('Amplitude')
  plt.axis('off')

  plt.subplot(132)
  plt.imshow(np.angle(superpos).reshape([npoints] * 2))
  plt.title('Phase')
  plt.axis('off')

  plt.subplot(133)
  plt.imshow(intensity.reshape([npoints] * 2))
  plt.title('Intensity')
  plt.axis('off')

  plt.show()
  return intensity

import torch

# Function to calculate fidelity
def calculate_fidelity(outputs, ground_truths):
    fidelities = []

    # Iterate through each output and ground truth pair
    for output, ground_truth in zip(outputs, ground_truths):
        # Normalize output and ground truth samples
        output_norm = output / torch.norm(output)
        ground_truth_norm = ground_truth / torch.norm(ground_truth)

        # Calculate inner product
        inner_product = torch.dot(output_norm, ground_truth_norm)

        # Calculate fidelity (square of absolute value of inner product)
        fidelity = torch.abs(inner_product) ** 2

        # Append fidelity to list
        fidelities.append(fidelity.item())  # Convert to scalar value

    return fidelities

model.eval()
test_losses = 0
correlation_values = []
fidelity_values = []  # Store fidelity values
with torch.no_grad():
    correct = 0
    total = 0
    i = 0
    for X, y in test_loader:

        X, y = X.to(device), y.to(device)
        out = model(X)
        test_losses += criterion(out, y)
        for out_single, y_single in zip(out, y):
            i = i + 1
            print('Test image {:3}:'.format(i), end=' ')
            pred_int = plot_fn(out_single)
            print('Ground Truth image {:3}:'.format(i), end=' ')
            gt_int = plot_fn(y_single)

            # Calculate correlation coefficient
            r = np.corrcoef(pred_int, gt_int)
            correlation_values.append(r[1, 0])
            print('Correlation:', correlation_values[i - 1])

            # Calculate fidelity
            fidelity = np.abs(np.sum(np.conj(pred_int) * gt_int)) / (
                        np.sqrt(np.sum(np.abs(pred_int) ** 2)) * np.sqrt(np.sum(np.abs(gt_int) ** 2)))
            fidelity_values.append(fidelity)
            print('Fidelity:', fidelity)

    print('Testing Loss = ', end=' ')
    print((test_losses / len(test_loader)).cpu().numpy())

# Calculate average fidelity
avg_fidelity = np.mean(fidelity_values)
print('Average Fidelity:', avg_fidelity)

# Generate graphs
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.plot(correlation_values, label='Correlation')
plt.xlabel('Image Index')
plt.ylabel('Correlation')
plt.title('Correlation Values')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(fidelity_values, label='Fidelity')
plt.xlabel('Image Index')
plt.ylabel('Fidelity')
plt.title('Fidelity Values')
plt.legend()

plt.tight_layout()
plt.show()

NOW FOR 2K SAMPLES

pip install pyMMF

import pyMMF
import numpy as np
import matplotlib.pyplot as plt
import time

# Find modes of an MMF
NA = 0.1
radius = 12.5 # in microns
areaSize = 2.5*radius # calculate the field on an area larger than the diameter of the fiber
npoints = 2**7 # resolution of the window
n1 = 1.45
wl = 0.532 # wavelength in microns
curvature = None

profile = pyMMF.IndexProfile(npoints = npoints, areaSize = areaSize)
profile.initStepIndex(n1=n1, a=radius, NA=NA)

solver = pyMMF.propagationModeSolver()
solver.setIndexProfile(profile)
solver.setWL(wl)

NmodesMax = pyMMF.estimateNumModesSI(wl,radius,NA,pola = 1)

modes = solver.solve (mode = 'SI', curvature = None)
modes.sort() # sort modes by descending beta constants

#Set the number of modes and generate a random complex matrix
random_matrix = np.random.rand(NmodesMax, NmodesMax) + 1j * np.random.rand(NmodesMax, NmodesMax)

 #Perform Singular Value Decomposition (SVD)
U, S, V = np.linalg.svd(random_matrix)
TM = U
print("Random complex matrix U from SVD:")
print(U)

# Number of modes in the few-mode fiber
total_modes = 5 # Modify this as needed

# Initialize the matrix to store the few-mode vectors
fiber_modes_matrix = []
GROUND_TRUTH = []

# Create random amplitude and phase for few-mode-number of modes
for _ in range(2000):  # N is the number of vectors you want to generate
    a = np.random.normal(0, 1, size=total_modes)
    phi = np.random.normal(0, 2 * np.pi, size=total_modes)
    phi[0] = 0

    # complex vector
    fiber_modes_nn = a * np.exp(1j * phi)
    fiber_modes_nn = fiber_modes_nn / np.linalg.norm(fiber_modes_nn)
    GROUND_TRUTH.append(fiber_modes_nn)

    # pad few-mode vector to multimode vector
    fiber_modes = np.pad(fiber_modes_nn, (0, NmodesMax - len(fiber_modes_nn) % 1024), 'constant')

    # Append the vector to the matrix
    fiber_modes_matrix.append(fiber_modes)

GROUND_TRUTH = np.array(GROUND_TRUTH)

# Convert the matrix to a numpy array
fiber_modes_matrix = np.array(fiber_modes_matrix)

# Display the generated few-mode vectors
print("Few-Mode Vectors Matrix:")
print(fiber_modes_matrix)

INPUTS = []
# Loop over each vector and calculate the superposition and intensity
for i in range(2000):
    fiber_modes = fiber_modes_matrix[i]

    # Calculate the MMF output vector y as y = TM * x
    y = np.dot(fiber_modes, TM)

    # Superposition of modes
    superpos = sum(y[i] * modes.profiles[i] for i in range(NmodesMax))
    '''
   # Display the results

    plt.figure()
    plt.subplot(121)
    plt.imshow(np.abs(superpos).reshape([npoints] * 2), cmap='viridis')
    plt.title(f'Amplitude-Superposition(Vector {i+1})')

    # Calculate the intensity
    intensity = np.abs(superpos) ** 2
    INPUTS.append(intensity.reshape([npoints]*2))

    plt.subplot(122)
    plt.imshow(intensity.reshape([npoints]*2), cmap='viridis')
    plt.title(f'Intensity-(Vector {i+1})')



plt.show()
'''

pip install complexPyTorch

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms

from torch.nn import BatchNorm2d, Conv2d, Linear
from torch.nn.functional import relu, max_pool2d
from torch.utils.data import DataLoader, TensorDataset, Subset

from complexPyTorch.complexLayers import ComplexBatchNorm2d, ComplexConv2d, ComplexLinear
from complexPyTorch.complexFunctions import complex_relu, complex_max_pool2d, complex_avg_pool2d


#import pyMMF
import numpy as np
import matplotlib.pyplot as plt
import time
import sys
import math
import cmath

OUTPUT_MODES = 5

BATCH_SIZE = 32
EPOCHS = 200

x = torch.tensor(INPUTS,dtype=torch.complex64)
y = torch.tensor(GROUND_TRUTH,dtype=torch.complex64)
#real_part = np.real(y)
#imaginary_part = np.imag(y)

# Stack them horizontally to get real and imaginary parts as separate values
#y = torch.tensor(np.hstack((real_part, imaginary_part)),dtype=torch.float32)

print(x.shape, y.shape)
print(x.dtype, y.dtype)
#print(x)
print(y)


dataset = TensorDataset(x, y)
#train_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

train_data, test_data, val_data = torch.utils.data.random_split(dataset,[0.72, 0.2, 0.08])

train_loader = DataLoader(train_data, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_data, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_data, batch_size=BATCH_SIZE, shuffle=True)

class ComplexNet(nn.Module):

    def __init__(self, output_modes, kernel_size):
        super(ComplexNet, self).__init__()
        '''
        self.conv1 = ComplexConv2d(1, 8,kernel_size)
        self.bn1  = ComplexBatchNorm2d(8)
        self.size_1 = int(np.floor((128 - kernel_size + 1 - 2)/2) + 1)

        self.conv2 = ComplexConv2d(8, 16,kernel_size)
        self.bn2  = ComplexBatchNorm2d(16)
        self.size_2 = int(np.floor((self.size_1 - kernel_size + 1 - 2)/2) + 1)

        self.conv3 = ComplexConv2d(16, 32,kernel_size)
        self.bn3  = ComplexBatchNorm2d(32)
        self.size_3 = int(np.floor((self.size_2 - kernel_size + 1 - 2)/2) + 1)

        self.fc1 = ComplexLinear(self.size_3*self.size_3*32, output_modes)
        '''
        self.fc_single = ComplexLinear(128*128, output_modes)

    def forward(self,x):
        '''x = x.view(x.size(0), 1,x.size(1),x.size(2))
        print(x.shape)

        x = self.conv1(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn1(x)

        x = self.conv2(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn2(x)

        x = self.conv3(x)
        x = complex_relu(x)
        x = complex_avg_pool2d(x, 2, 2)
        #x = self.bn3(x)
        '''
        x = x.view(-1,128*128)
        x = self.fc_single(x)
        '''print(x.shape)
        x = x.view(self.size_3*self.size_3*32)
        x = self.fc1(x)'''
        #x = x.abs()
        #x =  F.log_softmax(x, dim=1)
        return x

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = ComplexNet(kernel_size = 3, output_modes = OUTPUT_MODES).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)#, momentum=0.9)

train_losses = []
val_losses = []
def criterion(x, y):
    """
    Calculate the mean square error between two complex numbers of type torch.complex64.

    Args:
    x (torch.complex64): The first complex number.
    y (torch.complex64): The second complex number.

    Returns:
    mse (torch.float32): The mean square error between x and y.
    """
    # Calculate the squared difference between real and imaginary parts
    real_diff = torch.square(torch.real(x) - torch.real(y))
    imag_diff = torch.square(torch.imag(x) - torch.imag(y))

    # Calculate the mean square error
    mse = torch.mean(real_diff + imag_diff)
    #return (0.5*(x - y)**2).mean(dtype=torch.complex64)
    return mse

def eval(model, device, data_loader):
    model.eval()
    loss = 0
    for batch_idx, (data, target) in enumerate(data_loader):
        with torch.no_grad():
            data, target = data.to(device), target.to(device)
            output = model(data)

            loss += criterion(output, target)

    model.train()
    return loss/len(data_loader)


def train(model, device, train_loader, optimizer, epoch):
    model.train()
    epoch_loss = 0
    epoch_val_loss = 0
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)

        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        val_loss = eval(model, device, val_loader)
        print('\rTrain Epoch: {:3} [({:3.0f}%)]\tLoss: {:.6f}\tValidation Loss: {:.6f}'.format(
                epoch,
                100. * batch_idx / len(train_loader),
                loss.item(),
                val_loss),
              end = ' '
        )
        epoch_loss = loss.item()
        epoch_val_loss = eval(model, device, val_loader).cpu().numpy()
    train_losses.append(loss.item())
    val_losses.append(eval(model, device, val_loader).cpu().numpy())
    print('')

# Run training on 50 epochs
for epoch in range(EPOCHS):
    train(model, device, train_loader, optimizer, epoch)

plt.plot(range(len(train_losses)-2), train_losses[2:], label='Train Losses')
#val_losses = [tensor_item.cpu().numpy().item() for tensor_item in val_losses]
plt.plot(range(len(train_losses)-2), val_losses[2:], label='Validation Losses')

plt.xlabel('Batches')
plt.ylabel('Loss')

plt.title('Train and Validation Losses')

plt.legend()
plt.show()

import pyMMF
import numpy as np
import matplotlib.pyplot as plt
import time

# Find modes of an MMF
NA = 0.1
radius = 4 # in microns
areaSize = 2.5*radius # calculate the field on an area larger than the diameter of the fiber
npoints = 2**7 # resolution of the window
n1 = 1.45
wl = 0.589 # wavelength in microns
curvature = None
profile = pyMMF.IndexProfile(npoints = npoints, areaSize = areaSize)
profile.initStepIndex(n1=n1, a=radius, NA=NA)

solver = pyMMF.propagationModeSolver()
solver.setIndexProfile(profile)
solver.setWL(wl)
NmodesMax = pyMMF.estimateNumModesSI(wl,radius,NA,pola = 1)
print(NmodesMax)
modes = solver.solve (mode = 'SI', curvature = None)
modes.sort() # sort modes by descending beta constants

m = 2
plt.figure()
plt.subplot(121)
plt.imshow(np.abs(modes.profiles[m]).reshape([npoints]*2))
plt.title('Amplitude')
plt.subplot(122)
plt.imshow(np.angle(modes.profiles[m]).reshape([npoints]*2))
plt.title('Phase')


# show first n modes to check order of sort
plt.figure()
for i in range(NmodesMax):
    plt.subplot(7,7,i+1)
    plt.imshow(np.abs(modes.profiles[i].reshape([npoints]*2)))

def plot_fn(out_from_test):#output of nn for single image: 5 modes
# generate variable 'modes' using pymmf solver for 5 modes

  a = []
  phi = []
  for y in out_from_test:
      a.append(abs(y.cpu().numpy()))
      phi.append(cmath.phase(y))
  #print(a)
  #print(phi)
  weights = out_from_test.cpu().numpy()#a * np.exp(1j * phi)

  #print('Vector of mode weights:')
  #print(weights)

  #Create Superposition
  superpos = sum(weights[i] * modes.profiles[i] for i in range(NmodesMax))


  # Calculate intensity in MMF
  intensity = superpos * np.conj(superpos)
  intensity = np.real(intensity) # only to change data type from complex to float

  # Visualize the superposition
  plt.figure()
  plt.subplot(131)
  plt.imshow(np.abs(superpos).reshape([npoints] * 2))
  plt.title('Amplitude')
  plt.axis('off')

  plt.subplot(132)
  plt.imshow(np.angle(superpos).reshape([npoints] * 2))
  plt.title('Phase')
  plt.axis('off')

  plt.subplot(133)
  plt.imshow(intensity.reshape([npoints] * 2))
  plt.title('Intensity')
  plt.axis('off')

  plt.show()
  return intensity

import torch

# Function to calculate fidelity
def calculate_fidelity(outputs, ground_truths):
    fidelities = []

    # Iterate through each output and ground truth pair
    for output, ground_truth in zip(outputs, ground_truths):
        # Normalize output and ground truth samples
        output_norm = output / torch.norm(output)
        ground_truth_norm = ground_truth / torch.norm(ground_truth)

        # Calculate inner product
        inner_product = torch.dot(output_norm, ground_truth_norm)

        # Calculate fidelity (square of absolute value of inner product)
        fidelity = torch.abs(inner_product) ** 2

        # Append fidelity to list
        fidelities.append(fidelity.item())  # Convert to scalar value

    return fidelities

model.eval()
test_losses = 0
correlation_values = []
fidelity_values = []  # Store fidelity values
with torch.no_grad():
    correct = 0
    total = 0
    i = 0
    for X, y in test_loader:

        X, y = X.to(device), y.to(device)
        out = model(X)
        test_losses += criterion(out, y)
        for out_single, y_single in zip(out, y):
            i = i + 1
            print('Test image {:3}:'.format(i), end=' ')
            pred_int = plot_fn(out_single)
            print('Ground Truth image {:3}:'.format(i), end=' ')
            gt_int = plot_fn(y_single)

            # Calculate correlation coefficient
            r = np.corrcoef(pred_int, gt_int)
            correlation_values.append(r[1, 0])
            print('Correlation:', correlation_values[i - 1])

            # Calculate fidelity
            fidelity = np.abs(np.sum(np.conj(pred_int) * gt_int)) / (
                        np.sqrt(np.sum(np.abs(pred_int) ** 2)) * np.sqrt(np.sum(np.abs(gt_int) ** 2)))
            fidelity_values.append(fidelity)
            print('Fidelity:', fidelity)

    print('Testing Loss = ', end=' ')
    print((test_losses / len(test_loader)).cpu().numpy())

# Calculate average fidelity
avg_fidelity = np.mean(fidelity_values)
print('Average Fidelity:', avg_fidelity)

# Generate graphs
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.plot(correlation_values, label='Correlation')
plt.xlabel('Image Index')
plt.ylabel('Correlation')
plt.title('Correlation Values')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(fidelity_values, label='Fidelity')
plt.xlabel('Image Index')
plt.ylabel('Fidelity')
plt.title('Fidelity Values')
plt.legend()

plt.tight_layout()
plt.show()

